### ISSUE TITLE
After login forward to requested URL

### ISSUE THREAD

**Issue by arraen** [thesamet/gerrit-saml-plugin#14]
Is there is any way or ideas how to do forwarding of the user to requested URL instead of the main page?
Particularly interested in the ADFS case

**Comment by mikelupo** [comment]
@arraen 
I suspect that the crux of the problem is that the "Referer" header is (seemingly) hard coded to /gerrit/login.
What I believe the plugin has to do is instead capture the initial request, (i.e. https://gerrit.masked.com/gerrit/#/c/7202/) and then set that as the Referrer header in its request to the idP. There may be extra steps involved in getting it on this request to the idP.

@thesamet, can you comment on how this could potentially properly redirect to deep-linked urls on a given site? Thank you in advance!

Snipped from from the REQUEST headers:
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Connection: keep-alive
Content-Length: 4295
Content-Type: application/x-www-form-urlencoded
Host: idp-hoodat.masked.com
Origin: https://gerrit.masked.com
**Referer: https://gerrit.masked.com/gerrit/login/**

**Comment by thesamet** [comment]
Hi there! This repository is being discontinued and development continues at https://gerrit.googlesource.com/plugins/saml/

Please submit further issues directly to the Gerrit project.
